add start

diff --git a/bin/favo b/bin/favo
--- a/bin/favo
+++ b/bin/favo
@@ -421,7 +421,22 @@ trash_favo() {
 
 #将图片设置为桌面背景
 wallpaper_favo() {
-  sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}'" && killall Dock
+  METHOD=$(sw_vers -productVersion | awk -F'.' '{ if ($1 < 10 || $2 < 9) { print "osascript" } else{ print "sqlite3"  } }')
+  case $METHOD in
+      osascript)
+          osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"${1}\""
+          ;;
+      sqlite3)
+          current_path=$(sqlite3 -noheader -batch ${HOME}/Library/Application\ Support/Dock/desktoppicture.db 'select value from data limit 1')
+          if [[ "$current_path" != "$1" ]]; then
+              sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}'" && killall Dock
+          fi
+          ;;
+      *)
+          echo "I can't set the wallpaper" && exit 1
+          ;;
+  esac
+  #sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}'" && killall Dock
 }
 
 source $MYRUNTIME/customs/bin/mymessage
