update some custom function

diff --git a/bin/novel b/bin/novel
--- a/bin/novel
+++ b/bin/novel
@@ -1,152 +1,183 @@
 #!/usr/bin/env bash
-##Desc:小说管理
-##Author:杨浩
+### Desc:下载小说及管理小说
+### Date:2025-08-19
 
-MYRUNTIME=$(cat $HOME/.myruntime)
-NOVELPATH=$HOME/Documents/novels
-PYTHONCOMMAND=/usr/bin/python
-NOVELPYTHON=$MYRUNTIME/customs/others/getnovel.py
-NOVELEXT=txt
 
 [[ -f $MYRUNTIME/customs/my_shell/library/core/bzsh/core_common.bzsh ]] && source $MYRUNTIME/customs/my_shell/library/core/bzsh/core_common.bzsh
-custom_gum_show2hide_header "小说管理"
 
+NOVELSPATH=$(cat $HOME/.novelspath)
 
-novellists=$(ls ${NOVELPATH}/*${NOVELEXT})
-posit=0
-for novel in $novellists; do
-  novellists[$posit]=$novel
-  ((posit+=1))
-done
+[[ "" = "$NOVELSPATH" ]] && echo "Novels path does not set ..." && exit 1
+[[ ! -d "$NOVELSPATH" ]] && mkdir -p $NOVELSPATH
 
-getNovel() {
-  $PYTHONCOMMAND $NOVELPYTHON
-}
-
-listNovel() {
-  posit=0
-  echo "╭──────────────────────────────────────────────────────────────────────────────────────── -- - ･" | lolcat -f -F 0.05
-  for i in ${novellists[*]}; do
-    if [ -f $i ]; then
-      desc=$(head -n 1 $i)
-      desc=${desc:0:35}
-      name=$(basename $i)
-      printf "\033[0;33m│\033[0m\033[1;32m%-60s %-18s %-14s\033[0m\n"  "|" "| $posit" "| $name" "| $desc"
-      ((posit+=1))
+function novels_read() {
+    custom_gum_show2hide_header "小说阅读列表"
+    local choose=$(ls $NOVELSPATH/ | awk -v dir="$current_dir" '
+                { print }
+                END { print "↩️ 返回" }
+            ' | fzf +m $FZF_CUSTOM_PARAMS --preview="$MYRUNTIME/customs/bin/_previewer $NOVELSPATH/{}")
+    if [[ "$choose" == "↩️ 返回" ]]; then
+        return
+    elif [ "" != "$choose" ]; then
+        $MYRUNTIME/customs/bin/reader $NOVELSPATH/$choose
     fi
-  done
-  echo "╰──────────────────────────────────────────────────────────────────────────────────────── -- - ･" | lolcat -f -F 0.05
 }
 
-delNovel() {
-  if [ "" != "$1" ]; then
-    number=$1;
-  else
-    listNovel
-    echo "Which one do you want to delete?:";
-    read number;
-  fi
-  if [ "$number" -lt "0" ] || [ "${novellists[$number]}" = "" ]; then
-    echo "Your choice does not exists !"
-    return 1
-  else
-    trash ${novellists[$number]}
-  fi
-  if [ "$?" = "0" ]; then
-    echo "Delete Successful !"
-    return 0
-  else
-    echo "Delete Failure !"
-    return 1
-  fi
+function __clean_url() {
+    local url="$1"
+    [ -z "$url" ] && echo "" && return
+    
+    # 去除开头的协议和冒号
+    url=${url#http://}
+    url=${url#https://}
+    url=${url#http:}
+    url=${url#https:}
+    url=${url#:}
+    
+    # 去除结尾的斜杠（递归移除直到没有结尾斜杠）
+    while [ -n "$url" ] && [ "${url%"${url#?}"}" = '/' ]; do
+        url=${url%/}
+    done
+    
+    echo "$url"
 }
 
-viewNovel() {
-  if [ "" != "$1" ]; then
-    number=$1;
-  else
-    listNovel
-    echo "Which one do you want to view?:";
-    read number;
-  fi
-  if [ "$number" -lt "0" ] || [ "${novellists[$number]}" = "" ]; then
-    echo "Your choice does not exists !"
-    return 1
-  else
-    cat ${novellists[$number]} | iconv -t utf8| more
-  fi
-  return 0
+function novels_web_manager() {
+    custom_gum_show2hide_header "小说网站管理"
+    local novelsmark=$MYRUNTIME/tools/m_novels_mark
+    local OPENBROWSER='Brave Browser'
+    [[ ! -f $novelsmark ]] && touch $novelsmark
+
+    builtin cd $NOVELSPATH
+
+    local url=$(cat "$novelsmark" | awk -v dir="$current_dir" '
+                { print }
+                END { print "↩️ 返回" }
+            ' | fzf \
+    +m \
+    --delimiter='#' \
+    --with-nth=1 \
+    --header="🌐 选择网址 (单选) [${header%%#*}]" \
+    --preview='echo "{1}\n{2}"' \
+    --preview-window="right:70%:wrap" \
+	--height=95% \
+    --bind="ctrl-y:execute-silent(printf '%s' {2} | pbcopy)+abort" \
+    --bind="ctrl-e:execute(nvim \"$novelsmark\" < /dev/tty > /dev/tty)+reload(cat \"$novelsmark\")" \
+    --bind="ctrl-o:execute(open -a \"$OPENBROWSER\" {2})+abort" \
+    --bind="ctrl-h:change-preview-label( ╢ Help Infomation ╟ )+preview($MYRUNTIME/customs/bin/web help)+show-preview" \
+    --header-first \
+    --footer="Ctrl-Y 复制 | Ctrl-E 编辑 | Ctrl-O 浏览器打开网址 | Ctrl-h 帮助" \
+    --prompt="➤ " | \
+    awk -F'#' '{print $2}')
+    
+    [[ -z "$url" ]] && return
+    local cleanname=$(__clean_url $url)
+    local options=(
+        "编辑小说Ids"
+        "打开网址"
+        "执行下载"
+        "编辑下载脚本"
+        "↩️ 返回"
+    )
+    while true; do
+        selected=${1-$(printf '%s\n' "${options[@]}" | fzf \
+            --ansi \
+            --height=40% \
+            --reverse \
+            --prompt="➤ 主菜单 > " \
+            --header="请选择功能模块" \
+            --color="header:" \
+            --preview="echo -e '\n按 Enter 选择功能模块'"
+        )}
+        case "$selected" in
+            *编辑小说Ids*)
+                custom_gum_show2hide_header "编辑小说Ids"
+                # 用code或nvim
+                nvim ${cleanname}/${cleanname}ids.log
+                ;;
+            *打开网址*)
+                custom_gum_show2hide_header "打开网址"
+                open -a "$OPENBROWSER" $url
+                ;;
+            *执行下载*)
+                custom_gum_show2hide_header "执行下载"
+                cd ${cleanname} && bash ${cleanname}.multype.sh
+                ;;
+            *编辑下载脚本*)
+                custom_gum_show2hide_header "编辑下载脚本"
+                code ${cleanname}/
+                ;;
+            *)
+                return
+                ;;
+        esac
+    done
+    builtin cd -
 }
 
-openNovel() {
-  if [ "" != "$1" ]; then
-    number=$1;
-  else
-    listNovel
-    echo "Which one do you want to view?:";
-    read number;
-  fi
-  if [ "$number" -lt "0" ] || [ "${novellists[$number]}" = "" ]; then
-    echo "Your choice does not exists !"
-    return 1
-  else
-     open -a /Applications/Google\ Chrome.app ${novellists[$number]}
-  fi
-  return 0
-}
-
-truncateNovel() {
-  trash ${NOVELPATH}/*${NOVELEXT}
-  if [ "$?" = "0" ]; then
-    echo "Truncate Successful !"
-    return 0
-  else
-    echo "Truncate Failure !"
-    return 1
-  fi
-}
-
-helpNovel() {
-  echo "╭──────────────────────────────────────────────────────────────────────────────────────── -- - ･
+function novels_help() {
+    custom_gum_show2hide_header "帮助"
+    echo "╭──────────────────────────────────────────────────────────────────────────────────────── -- - ･
 │ 使用方法: ${0##*/} [command(可用命令)]
 ╰──────────────────────────────────────────────────────────────────────────────────────── -- - ･" | lolcat -f -F 0.05
-echo "╭──────────────────────────────────────────────────────────────────────────────────────── -- - ･
+    echo "╭──────────────────────────────────────────────────────────────────────────────────────── -- - ･
 │ 使用方法: ${0##*/} [command]
 │ command(可用命令):
-│  list      / l   列表
-│  get       / g   获取
-│  del       / d   删除
-│  open      / o   打开
-│  view      / v   查看
-│  trun      / t   清空
-│  help      / h   帮助
+│  statistics      / s   统计数量及磁盘占用量
+│  choose          / c   小说阅读列表
+│  directory       / d   打开小说文件夹
+│  web             / w   小说网站管理
+│  help            / h   帮助
 ╰──────────────────────────────────────────────────────────────────────────────────────── -- - ･" | lolcat -f -F 0.05
 }
 
-# source $MYRUNTIME/customs/bin/mymessage
+options=(
+    "统计数量及磁盘占用量"
+    "打开小说文件夹"
+    "小说阅读列表"
+    "小说网站管理"
+    "帮助"
+    "↩️ 返回"
+)
 
-case "$1" in
-  "get"|"g")
-    getNovel
-    ;;
-  "list"|"l")
-    listNovel
-    ;;
-  "view"|"v")
-    viewNovel $2
-    ;;
-  "open"|"o")
-    openNovel $2
-    ;;
-  "truncate"|"t")
-    truncateNovel
-    ;;
-  "delete"|"del"|"d")
-    delNovel $2
-    ;;
-  "help"|"h"|*)
-    helpNovel
-    echo ""
-    listNovel
-    ;;
+selected=${1-$(printf '%s\n' "${options[@]}" | fzf \
+        --ansi \
+        --height=40% \
+        --reverse \
+        --prompt="➤ 主菜单 > " \
+        --header="请选择功能模块" \
+        --color="header:" \
+        --preview="echo -e '\n按 Enter 选择功能模块'"
+    )}
+if [ ! -z "$2" ] && [ "$2" = "source" ]; then
+	[[ -z "$selected" ]] && break
+	[[ $selected =~ 返回 ]] && break
+fi
+case "$selected" in
+    "statistics" | "s" | *统计数量及磁盘占用量*)
+        custom_gum_show2hide_header "统计数量及磁盘占用量"
+        echo "Novels Num:"
+        ls $NOVELSPATH/ | wc -l
+        echo "Novels Size:"
+        /usr/bin/du -sh $NOVELSPATH | awk '{print $1}'
+        ;;
+    "directory" | "d" | *打开小说文件夹*)
+        custom_gum_show2hide_header "打开小说文件夹"
+        open $NOVELSPATH
+        ;;
+    "choose" | "c" | *小说阅读列表*)
+        novels_read
+        ;;
+    "web" | "w" | *小说网站管理*)
+        novels_web_manager
+        ;;
+    "help" | "h" | *帮助*)
+        novels_help
+        ;;
+    *返回* | *)
+        if [ ! -z "$2" ] && [ "$2" = "source" ]; then
+            break
+            return
+        fi
+        ;;
 esac
